### PR TITLE
Fix performance related bugs

### LINKED ISSUE #576: Some components do not re-render
Since we made the performance improvements, some components will not be re-rendered after changes were made (see example below).

**Before switching language**
image

**After switching language**
image

**After changing a property** (in this case, increasing radius)
image

### PR DESCRIPTION
**Pull request by jansule**
Some components did not update properly since our performance optimizations. Especially switching languages did not work properly, due to some parent components not having locales on their own, and thus, not updating child components. This PR fixes this.

Also added `build:dist` as default task to vscode to run it with `ctrl + shift + b` from within vscode.

Note: FilterTree is still quite slow in comparison to the other components. Relates to #505 

Closes #576

### CODE REVIEW

File: src/Component/Filter/FilterTree/FilterTree.tsx [hunk 1]
```diff
@@ -323,7 +347,8 @@ export class FilterTree extends React.Component<FilterTreeProps, FilterTreeState
     } = this.props;
 
     let addedFilter: GsFilter ;
-    const newFilter: GsFilter = [...filter];
+    // const newFilter: GsFilter = [...filter];
```
Comment (hwbllmnn) [inline src/Component/Filter/FilterTree/FilterTree.tsx]: Commented code
